FINALPACKAGE = 1
THEOS_DEVICE_IP = 192.168.1.8

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/null.mk

all::
	xcodebuild CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES -scheme Aphrodite -destination generic/platform=iOS archive -archivePath Aphrodite.xcarchive PACKAGE_VERSION='@\"$(THEOS_PACKAGE_VERSION)\"' | xcpretty && exit ${PIPESTATUS[0]}

before-stage::
	find . -name ".DS_Store" -type f -delete

after-stage::
	mv Aphrodite.xcarchive/Products/Applications $(THEOS_STAGING_DIR)/Applications
	rm -rf Aphrodite.xcarchive
	ldid -S $(THEOS_STAGING_DIR)/Applications/Aphrodite.app/Aphrodite
	ldid -SAphrodite/Aphrodite.entitlements $(THEOS_STAGING_DIR)/Applications/Aphrodite.app/Aphrodite


all::
	$(info $(bold)$(yellow))
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWV  VWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.  .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWV.  .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWV.           WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWV.                        WWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWW.              _               WWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWW.     _        AWWWA.        __     WWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWW.      AWA.     AWWWWWWWW.      AWW.     WWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWW.      WWWW.     AWWWWWWWWWWW.     WWWW.     WWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWW.     WWWWW.    AWWWWWWWWWWWWWWW.    WWWWW.     WWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWW.    WWWWWW.    AWWWWWWWWWWWWWWWWW.    WWWWWA.    WWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWW.    WWWWWWW.   AWWWWWWWWWWWWWWWWWWW.    WWWWWA.     WWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWW.    WWWWWWW.    WWWWWWWWWWWWWWWWWWWWW.   WWWWWWA.     WWWWWWWWWWW)
	$(info $WWWWWWWWWWWW.    WWWWWWWW.   WWWWWWWWWWWWWWWWWWWWWW     WWWWWW.     WWWWWWWWWWW)
	$(info $WWWWWWWWWWWW.   WWWWWWWW.    WWWWWWWWWWWWWWWWWWWWWW.    WWWWWWW.     WWWWWWWWWW)
	$(info $WWWWWWWWWWW.    WWWWWWWW.    WWWWWWWWWWWWWWWWWWWWWW.    WWWWWWW.     WWWWWWWWWW)
	$(info $WWWWWWWWWWW.                                                         WWWWWWWWWW)
	$(info $WWWWWWWWWWW.                                                         WWWWWWWWWW)
	$(info $WWWWWWWWWWWA.........................       ........................AWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWA      AWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWW:    WWWWWWWWI      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWA.    WWWWWWW       WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWW.      WWV        WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWA.              WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWA.           AWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWW                                                           WWWWWWWWWW)
	$(info $WWWWWWWWWW          $(clean)$(bold)Fight for Freedom. Stand with Hong Kong.         $(yellow)WWWWWWWWWW)
	$(info $WWWWWWWWWW                                                           WWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW)
	$(info $(clean))
